### PR TITLE
Corrects the WizardScope.hasNext getter

### LINKED ISSUE #19: hasNext getter is misleading for dynamically set wizards
By dynamically set I mean wizards that skip certain routes, like when we set the inital route to other than the first element of the routes map. In such cases the `widget._index` counts the number of routes that we actually passed by (not counting the ones we skipped), thus the comparison returns true even for the last element of the routes map.

```dart
  /// Returns `false` if the wizard page is the last page.
  bool get hasNext => widget._index < widget._routes.length - 1;
```

The test case below demonstrate the behavior reported. It consists with three routes, where the second is set as initial. The third (and last) route checks for `Wizard.of(context).hasNext`, but that is not enough to prevent calling `next()` from the last route, thus causing an assertion failure.

```dart
  testWidgets('hasNext returns false for the last route', (tester) async {
    await pumpWizardApp(
      tester,
      initialRoute: Routes.second,
      routes: {
        Routes.first: WizardRoute(builder: (_) => const Text(Routes.first)),
        Routes.second: WizardRoute(
          builder: (context) => ElevatedButton(
              child: Text(Routes.second), onPressed: Wizard.of(context).next),
        ),
        Routes.third: WizardRoute(
          builder: (context) => TextButton(
            child: Text(Routes.third),
            onPressed: () {
              final wiz = Wizard.of(context);
              // Third should never call next() because it's the last route.
              if (wiz.hasNext) wiz.next();
            },
          ),
        ),
      },
    );

    // We are on the second route.
    await tester.tap(find.byType(ElevatedButton));
    await tester.pumpAndSettle();

    //Now we should be on the third
    expect(find.text(Routes.first), findsNothing);
    expect(find.text(Routes.second), findsNothing);
    expect(find.text(Routes.third), findsOneWidget);

    // Nothing should happen now:
    await tester.tap(find.byType(TextButton));
    await tester.pumpAndSettle();

    expect(find.text(Routes.first), findsNothing);
    expect(find.text(Routes.second), findsNothing);
    expect(find.text(Routes.third), findsOneWidget);
  });

```

```
00:02 +3: hasNext should return false for the last route
══╡ EXCEPTION CAUGHT BY GESTURE ╞══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
`Wizard.next()` called from the last route /third.
'package:wizard_router/src/scope.dart':
Failed assertion: line 103 pos 14: 'index < widget._routes.length - 1'


```

The solution is baked inside the `WizardScope.next()` method. Unfortunately that will make the hasNext getter to be more expensive.

### PR DESCRIPTION
**Pull request by CarlosNihelton**
Fixes #19

### CODE REVIEW

**Review by jpnurmi — COMMENTED** [review]
what if we would go the other way around and fix the list of routes that are passed to WizardScope to make the index match? (and leave out routes that effectively don't exist.) something like `routes.skipWhile((route) => route != initialRoute)` should do the trick?

**Comment by CarlosNihelton** [comment]
> what if we would go the other way around and fix the list of routes that are passed to WizardScope to make the index match? (and leave out routes that effectively don't exist.) something like `routes.skipWhile((route) => route != initialRoute)` should do the trick?

I guess that fixes the initialRoute issue, but what happens if a route is skipped dynamically due some creative `onNext()` in the middle of the wizard flow?

**Comment by CarlosNihelton** [comment]
> Hmm, sounds like the whole idea of using an index number to denote the current position broke after adding support for dynamic conditions. 😄
> 
> > but what happens if a route is skipped dynamically due some creative `onNext()` in the middle of the wizard flow?
> 
> Any chance to have a test for that too? :)

Sure. Sorry, I was in a hurry, I'll add a test case for that scenario as well.

**Comment by CarlosNihelton** [comment]
> routes.skipWhile((route) => route != initialRoute)

So, as we suspected this fixes my original reports, but fails when a WizardRoute skips a neighbour using its `onNext()`:

```dart
child: WizardScope(
        index: index,
        route: widget.routes[settings.name]!,
        routes: widget.routes.keys
            .skipWhile((route) =>
                route != (widget.initialRoute ?? widget.routes.keys.first))
            .toList(),
      ),
 ```

```
00:04 +16: hasNext returns false for the last route on skip as well
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
`Wizard.next()` called from the last route /third.
'package:wizard_router/src/scope.dart':
Failed assertion: line 103 pos 14: 'index < widget._routes.length - 1'
```

I'm pushing the test and keeping the rest of the code as was, but I'll keep the change mentioned above in the commit history should you want to see it in action (git checkout HEAD~2 && flutter test)

**Review by jpnurmi — APPROVED** [review]
Great, thanks for adding the test! It'll be very helpful if we want to refactor later. :+1:

**Comment by CarlosNihelton** [comment]
> My bad, I thought you'd have the button as a member of the org. Did it show up now?

Yes, it does! Thank you!

**Pull request merged**
